server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql:///jmc?serverTimeZone=UTC
    username: root
    password: root

  cache:
    redis:
      # 设置redis每条数据的有效期为10分钟
      time-to-live: 600000
      # 不允许缓存null值
      cache-null-values: false

logging:
  level:
   com.jmc.mapper:
     DEBUG
